name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: cache
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_momdules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run lint
